# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phi/DEV/3d/asteroidfighter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phi/DEV/3d/asteroidfighter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles /home/phi/DEV/3d/asteroidfighter/Sprite3d/CMakeFiles/progress.marks
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Sprite3d/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Sprite3d/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Sprite3d/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Sprite3d/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Sprite3d/CMakeFiles/Sprite3d.dir/rule:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Sprite3d/CMakeFiles/Sprite3d.dir/rule
.PHONY : Sprite3d/CMakeFiles/Sprite3d.dir/rule

# Convenience name for target.
Sprite3d: Sprite3d/CMakeFiles/Sprite3d.dir/rule
.PHONY : Sprite3d

# fast build rule for target.
Sprite3d/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/build
.PHONY : Sprite3d/fast

AnimatObj.o: AnimatObj.cc.o
.PHONY : AnimatObj.o

# target to build an object file
AnimatObj.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/AnimatObj.cc.o
.PHONY : AnimatObj.cc.o

AnimatObj.i: AnimatObj.cc.i
.PHONY : AnimatObj.i

# target to preprocess a source file
AnimatObj.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/AnimatObj.cc.i
.PHONY : AnimatObj.cc.i

AnimatObj.s: AnimatObj.cc.s
.PHONY : AnimatObj.s

# target to generate assembly for a file
AnimatObj.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/AnimatObj.cc.s
.PHONY : AnimatObj.cc.s

Collision.o: Collision.cc.o
.PHONY : Collision.o

# target to build an object file
Collision.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Collision.cc.o
.PHONY : Collision.cc.o

Collision.i: Collision.cc.i
.PHONY : Collision.i

# target to preprocess a source file
Collision.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Collision.cc.i
.PHONY : Collision.cc.i

Collision.s: Collision.cc.s
.PHONY : Collision.s

# target to generate assembly for a file
Collision.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Collision.cc.s
.PHONY : Collision.cc.s

ObjOdron.o: ObjOdron.cc.o
.PHONY : ObjOdron.o

# target to build an object file
ObjOdron.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjOdron.cc.o
.PHONY : ObjOdron.cc.o

ObjOdron.i: ObjOdron.cc.i
.PHONY : ObjOdron.i

# target to preprocess a source file
ObjOdron.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjOdron.cc.i
.PHONY : ObjOdron.cc.i

ObjOdron.s: ObjOdron.cc.s
.PHONY : ObjOdron.s

# target to generate assembly for a file
ObjOdron.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjOdron.cc.s
.PHONY : ObjOdron.cc.s

ObjPart.o: ObjPart.cc.o
.PHONY : ObjPart.o

# target to build an object file
ObjPart.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjPart.cc.o
.PHONY : ObjPart.cc.o

ObjPart.i: ObjPart.cc.i
.PHONY : ObjPart.i

# target to preprocess a source file
ObjPart.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjPart.cc.i
.PHONY : ObjPart.cc.i

ObjPart.s: ObjPart.cc.s
.PHONY : ObjPart.s

# target to generate assembly for a file
ObjPart.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjPart.cc.s
.PHONY : ObjPart.cc.s

ObjPrim.o: ObjPrim.cc.o
.PHONY : ObjPrim.o

# target to build an object file
ObjPrim.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjPrim.cc.o
.PHONY : ObjPrim.cc.o

ObjPrim.i: ObjPrim.cc.i
.PHONY : ObjPrim.i

# target to preprocess a source file
ObjPrim.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjPrim.cc.i
.PHONY : ObjPrim.cc.i

ObjPrim.s: ObjPrim.cc.s
.PHONY : ObjPrim.s

# target to generate assembly for a file
ObjPrim.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjPrim.cc.s
.PHONY : ObjPrim.cc.s

ObjText2d.o: ObjText2d.cc.o
.PHONY : ObjText2d.o

# target to build an object file
ObjText2d.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjText2d.cc.o
.PHONY : ObjText2d.cc.o

ObjText2d.i: ObjText2d.cc.i
.PHONY : ObjText2d.i

# target to preprocess a source file
ObjText2d.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjText2d.cc.i
.PHONY : ObjText2d.cc.i

ObjText2d.s: ObjText2d.cc.s
.PHONY : ObjText2d.s

# target to generate assembly for a file
ObjText2d.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjText2d.cc.s
.PHONY : ObjText2d.cc.s

ObjVect.o: ObjVect.cc.o
.PHONY : ObjVect.o

# target to build an object file
ObjVect.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjVect.cc.o
.PHONY : ObjVect.cc.o

ObjVect.i: ObjVect.cc.i
.PHONY : ObjVect.i

# target to preprocess a source file
ObjVect.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjVect.cc.i
.PHONY : ObjVect.cc.i

ObjVect.s: ObjVect.cc.s
.PHONY : ObjVect.s

# target to generate assembly for a file
ObjVect.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/ObjVect.cc.s
.PHONY : ObjVect.cc.s

Random.o: Random.cc.o
.PHONY : Random.o

# target to build an object file
Random.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Random.cc.o
.PHONY : Random.cc.o

Random.i: Random.cc.i
.PHONY : Random.i

# target to preprocess a source file
Random.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Random.cc.i
.PHONY : Random.cc.i

Random.s: Random.cc.s
.PHONY : Random.s

# target to generate assembly for a file
Random.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Random.cc.s
.PHONY : Random.cc.s

SceneManager.o: SceneManager.cc.o
.PHONY : SceneManager.o

# target to build an object file
SceneManager.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SceneManager.cc.o
.PHONY : SceneManager.cc.o

SceneManager.i: SceneManager.cc.i
.PHONY : SceneManager.i

# target to preprocess a source file
SceneManager.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SceneManager.cc.i
.PHONY : SceneManager.cc.i

SceneManager.s: SceneManager.cc.s
.PHONY : SceneManager.s

# target to generate assembly for a file
SceneManager.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SceneManager.cc.s
.PHONY : SceneManager.cc.s

SoundControler.o: SoundControler.cc.o
.PHONY : SoundControler.o

# target to build an object file
SoundControler.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SoundControler.cc.o
.PHONY : SoundControler.cc.o

SoundControler.i: SoundControler.cc.i
.PHONY : SoundControler.i

# target to preprocess a source file
SoundControler.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SoundControler.cc.i
.PHONY : SoundControler.cc.i

SoundControler.s: SoundControler.cc.s
.PHONY : SoundControler.s

# target to generate assembly for a file
SoundControler.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SoundControler.cc.s
.PHONY : SoundControler.cc.s

SoundLibrary.o: SoundLibrary.cc.o
.PHONY : SoundLibrary.o

# target to build an object file
SoundLibrary.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SoundLibrary.cc.o
.PHONY : SoundLibrary.cc.o

SoundLibrary.i: SoundLibrary.cc.i
.PHONY : SoundLibrary.i

# target to preprocess a source file
SoundLibrary.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SoundLibrary.cc.i
.PHONY : SoundLibrary.cc.i

SoundLibrary.s: SoundLibrary.cc.s
.PHONY : SoundLibrary.s

# target to generate assembly for a file
SoundLibrary.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/SoundLibrary.cc.s
.PHONY : SoundLibrary.cc.s

Sprite3d.o: Sprite3d.cc.o
.PHONY : Sprite3d.o

# target to build an object file
Sprite3d.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3d.cc.o
.PHONY : Sprite3d.cc.o

Sprite3d.i: Sprite3d.cc.i
.PHONY : Sprite3d.i

# target to preprocess a source file
Sprite3d.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3d.cc.i
.PHONY : Sprite3d.cc.i

Sprite3d.s: Sprite3d.cc.s
.PHONY : Sprite3d.s

# target to generate assembly for a file
Sprite3d.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3d.cc.s
.PHONY : Sprite3d.cc.s

Sprite3dObj.o: Sprite3dObj.cc.o
.PHONY : Sprite3dObj.o

# target to build an object file
Sprite3dObj.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3dObj.cc.o
.PHONY : Sprite3dObj.cc.o

Sprite3dObj.i: Sprite3dObj.cc.i
.PHONY : Sprite3dObj.i

# target to preprocess a source file
Sprite3dObj.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3dObj.cc.i
.PHONY : Sprite3dObj.cc.i

Sprite3dObj.s: Sprite3dObj.cc.s
.PHONY : Sprite3dObj.s

# target to generate assembly for a file
Sprite3dObj.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3dObj.cc.s
.PHONY : Sprite3dObj.cc.s

Sprite3dPilot.o: Sprite3dPilot.cc.o
.PHONY : Sprite3dPilot.o

# target to build an object file
Sprite3dPilot.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3dPilot.cc.o
.PHONY : Sprite3dPilot.cc.o

Sprite3dPilot.i: Sprite3dPilot.cc.i
.PHONY : Sprite3dPilot.i

# target to preprocess a source file
Sprite3dPilot.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3dPilot.cc.i
.PHONY : Sprite3dPilot.cc.i

Sprite3dPilot.s: Sprite3dPilot.cc.s
.PHONY : Sprite3dPilot.s

# target to generate assembly for a file
Sprite3dPilot.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Sprite3dPilot.cc.s
.PHONY : Sprite3dPilot.cc.s

Text2d.o: Text2d.cc.o
.PHONY : Text2d.o

# target to build an object file
Text2d.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Text2d.cc.o
.PHONY : Text2d.cc.o

Text2d.i: Text2d.cc.i
.PHONY : Text2d.i

# target to preprocess a source file
Text2d.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Text2d.cc.i
.PHONY : Text2d.cc.i

Text2d.s: Text2d.cc.s
.PHONY : Text2d.s

# target to generate assembly for a file
Text2d.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Text2d.cc.s
.PHONY : Text2d.cc.s

Utils3d.o: Utils3d.cc.o
.PHONY : Utils3d.o

# target to build an object file
Utils3d.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Utils3d.cc.o
.PHONY : Utils3d.cc.o

Utils3d.i: Utils3d.cc.i
.PHONY : Utils3d.i

# target to preprocess a source file
Utils3d.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Utils3d.cc.i
.PHONY : Utils3d.cc.i

Utils3d.s: Utils3d.cc.s
.PHONY : Utils3d.s

# target to generate assembly for a file
Utils3d.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/Utils3d.cc.s
.PHONY : Utils3d.cc.s

World.o: World.cc.o
.PHONY : World.o

# target to build an object file
World.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/World.cc.o
.PHONY : World.cc.o

World.i: World.cc.i
.PHONY : World.i

# target to preprocess a source file
World.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/World.cc.i
.PHONY : World.cc.i

World.s: World.cc.s
.PHONY : World.s

# target to generate assembly for a file
World.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/World.cc.s
.PHONY : World.cc.s

WorldControler.o: WorldControler.cc.o
.PHONY : WorldControler.o

# target to build an object file
WorldControler.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/WorldControler.cc.o
.PHONY : WorldControler.cc.o

WorldControler.i: WorldControler.cc.i
.PHONY : WorldControler.i

# target to preprocess a source file
WorldControler.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/WorldControler.cc.i
.PHONY : WorldControler.cc.i

WorldControler.s: WorldControler.cc.s
.PHONY : WorldControler.s

# target to generate assembly for a file
WorldControler.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/WorldControler.cc.s
.PHONY : WorldControler.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Sprite3d"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AnimatObj.o"
	@echo "... AnimatObj.i"
	@echo "... AnimatObj.s"
	@echo "... Collision.o"
	@echo "... Collision.i"
	@echo "... Collision.s"
	@echo "... ObjOdron.o"
	@echo "... ObjOdron.i"
	@echo "... ObjOdron.s"
	@echo "... ObjPart.o"
	@echo "... ObjPart.i"
	@echo "... ObjPart.s"
	@echo "... ObjPrim.o"
	@echo "... ObjPrim.i"
	@echo "... ObjPrim.s"
	@echo "... ObjText2d.o"
	@echo "... ObjText2d.i"
	@echo "... ObjText2d.s"
	@echo "... ObjVect.o"
	@echo "... ObjVect.i"
	@echo "... ObjVect.s"
	@echo "... Random.o"
	@echo "... Random.i"
	@echo "... Random.s"
	@echo "... SceneManager.o"
	@echo "... SceneManager.i"
	@echo "... SceneManager.s"
	@echo "... SoundControler.o"
	@echo "... SoundControler.i"
	@echo "... SoundControler.s"
	@echo "... SoundLibrary.o"
	@echo "... SoundLibrary.i"
	@echo "... SoundLibrary.s"
	@echo "... Sprite3d.o"
	@echo "... Sprite3d.i"
	@echo "... Sprite3d.s"
	@echo "... Sprite3dObj.o"
	@echo "... Sprite3dObj.i"
	@echo "... Sprite3dObj.s"
	@echo "... Sprite3dPilot.o"
	@echo "... Sprite3dPilot.i"
	@echo "... Sprite3dPilot.s"
	@echo "... Text2d.o"
	@echo "... Text2d.i"
	@echo "... Text2d.s"
	@echo "... Utils3d.o"
	@echo "... Utils3d.i"
	@echo "... Utils3d.s"
	@echo "... World.o"
	@echo "... World.i"
	@echo "... World.s"
	@echo "... WorldControler.o"
	@echo "... WorldControler.i"
	@echo "... WorldControler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

