# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phi/DEV/3d/asteroidfighter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phi/DEV/3d/asteroidfighter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles /home/phi/DEV/3d/asteroidfighter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named T3d

# Build rule for target.
T3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T3d
.PHONY : T3d

# fast build rule for target.
T3d/fast:
	$(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/build
.PHONY : T3d/fast

#=============================================================================
# Target rules for targets named O3d

# Build rule for target.
O3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 O3d
.PHONY : O3d

# fast build rule for target.
O3d/fast:
	$(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/build
.PHONY : O3d/fast

#=============================================================================
# Target rules for targets named Sprite3d

# Build rule for target.
Sprite3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sprite3d
.PHONY : Sprite3d

# fast build rule for target.
Sprite3d/fast:
	$(MAKE) -f Sprite3d/CMakeFiles/Sprite3d.dir/build.make Sprite3d/CMakeFiles/Sprite3d.dir/build
.PHONY : Sprite3d/fast

#=============================================================================
# Target rules for targets named U3d

# Build rule for target.
U3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 U3d
.PHONY : U3d

# fast build rule for target.
U3d/fast:
	$(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/build
.PHONY : U3d/fast

#=============================================================================
# Target rules for targets named Space

# Build rule for target.
Space: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Space
.PHONY : Space

# fast build rule for target.
Space/fast:
	$(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/build
.PHONY : Space/fast

#=============================================================================
# Target rules for targets named AsteroidFighter

# Build rule for target.
AsteroidFighter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsteroidFighter
.PHONY : AsteroidFighter

# fast build rule for target.
AsteroidFighter/fast:
	$(MAKE) -f AsteroidFighter/CMakeFiles/AsteroidFighter.dir/build.make AsteroidFighter/CMakeFiles/AsteroidFighter.dir/build
.PHONY : AsteroidFighter/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... T3d"
	@echo "... O3d"
	@echo "... Sprite3d"
	@echo "... U3d"
	@echo "... Space"
	@echo "... AsteroidFighter"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

