all::
		cd T3d; make -f Makefile.old;cd ..;\
		cd O3d; make -f Makefile.old;cd ..;\
		cd Sprite3d; make -f Makefile.old;cd ..;\
	  cd U3d; make -f Makefile.old;cd ..;\
	  cd Space; make -f Makefile.old;cd ..;\
	  cd AsteroidFighter; make -f Makefile.old;cd ..;\
 
clean::
	cd T3d; make -f Makefile.old clean;cd ..;\
	cd O3d; make -f Makefile.old clean;cd ..;\
	cd Sprite3d; make -f Makefile.old clean;cd ..;\
	cd U3d; make -f Makefile.old clean;cd ..;\
	cd Space; make -f Makefile.old clean;cd ..;\
	cd AsteroidFighter; make -f Makefile.old clean;cd ..;\
	rm core AsteroidFighter AsteroidFighter.exe *.o  
	rm -rf Output/* OutputDebug/*
