# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phi/DEV/3d/asteroidfighter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phi/DEV/3d/asteroidfighter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles /home/phi/DEV/3d/asteroidfighter/O3d/CMakeFiles/progress.marks
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 O3d/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 O3d/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 O3d/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 O3d/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
O3d/CMakeFiles/O3d.dir/rule:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 O3d/CMakeFiles/O3d.dir/rule
.PHONY : O3d/CMakeFiles/O3d.dir/rule

# Convenience name for target.
O3d: O3d/CMakeFiles/O3d.dir/rule
.PHONY : O3d

# fast build rule for target.
O3d/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/build
.PHONY : O3d/fast

O3dKamera.o: O3dKamera.cc.o
.PHONY : O3dKamera.o

# target to build an object file
O3dKamera.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dKamera.cc.o
.PHONY : O3dKamera.cc.o

O3dKamera.i: O3dKamera.cc.i
.PHONY : O3dKamera.i

# target to preprocess a source file
O3dKamera.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dKamera.cc.i
.PHONY : O3dKamera.cc.i

O3dKamera.s: O3dKamera.cc.s
.PHONY : O3dKamera.s

# target to generate assembly for a file
O3dKamera.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dKamera.cc.s
.PHONY : O3dKamera.cc.s

O3dObj.o: O3dObj.cc.o
.PHONY : O3dObj.o

# target to build an object file
O3dObj.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObj.cc.o
.PHONY : O3dObj.cc.o

O3dObj.i: O3dObj.cc.i
.PHONY : O3dObj.i

# target to preprocess a source file
O3dObj.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObj.cc.i
.PHONY : O3dObj.cc.i

O3dObj.s: O3dObj.cc.s
.PHONY : O3dObj.s

# target to generate assembly for a file
O3dObj.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObj.cc.s
.PHONY : O3dObj.cc.s

O3dObjBSpline.o: O3dObjBSpline.cc.o
.PHONY : O3dObjBSpline.o

# target to build an object file
O3dObjBSpline.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBSpline.cc.o
.PHONY : O3dObjBSpline.cc.o

O3dObjBSpline.i: O3dObjBSpline.cc.i
.PHONY : O3dObjBSpline.i

# target to preprocess a source file
O3dObjBSpline.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBSpline.cc.i
.PHONY : O3dObjBSpline.cc.i

O3dObjBSpline.s: O3dObjBSpline.cc.s
.PHONY : O3dObjBSpline.s

# target to generate assembly for a file
O3dObjBSpline.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBSpline.cc.s
.PHONY : O3dObjBSpline.cc.s

O3dObjBSplineSurf.o: O3dObjBSplineSurf.cc.o
.PHONY : O3dObjBSplineSurf.o

# target to build an object file
O3dObjBSplineSurf.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBSplineSurf.cc.o
.PHONY : O3dObjBSplineSurf.cc.o

O3dObjBSplineSurf.i: O3dObjBSplineSurf.cc.i
.PHONY : O3dObjBSplineSurf.i

# target to preprocess a source file
O3dObjBSplineSurf.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBSplineSurf.cc.i
.PHONY : O3dObjBSplineSurf.cc.i

O3dObjBSplineSurf.s: O3dObjBSplineSurf.cc.s
.PHONY : O3dObjBSplineSurf.s

# target to generate assembly for a file
O3dObjBSplineSurf.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBSplineSurf.cc.s
.PHONY : O3dObjBSplineSurf.cc.s

O3dObjBezier.o: O3dObjBezier.cc.o
.PHONY : O3dObjBezier.o

# target to build an object file
O3dObjBezier.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBezier.cc.o
.PHONY : O3dObjBezier.cc.o

O3dObjBezier.i: O3dObjBezier.cc.i
.PHONY : O3dObjBezier.i

# target to preprocess a source file
O3dObjBezier.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBezier.cc.i
.PHONY : O3dObjBezier.cc.i

O3dObjBezier.s: O3dObjBezier.cc.s
.PHONY : O3dObjBezier.s

# target to generate assembly for a file
O3dObjBezier.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjBezier.cc.s
.PHONY : O3dObjBezier.cc.s

O3dObjFacet.o: O3dObjFacet.cc.o
.PHONY : O3dObjFacet.o

# target to build an object file
O3dObjFacet.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjFacet.cc.o
.PHONY : O3dObjFacet.cc.o

O3dObjFacet.i: O3dObjFacet.cc.i
.PHONY : O3dObjFacet.i

# target to preprocess a source file
O3dObjFacet.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjFacet.cc.i
.PHONY : O3dObjFacet.cc.i

O3dObjFacet.s: O3dObjFacet.cc.s
.PHONY : O3dObjFacet.s

# target to generate assembly for a file
O3dObjFacet.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjFacet.cc.s
.PHONY : O3dObjFacet.cc.s

O3dObjLight.o: O3dObjLight.cc.o
.PHONY : O3dObjLight.o

# target to build an object file
O3dObjLight.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjLight.cc.o
.PHONY : O3dObjLight.cc.o

O3dObjLight.i: O3dObjLight.cc.i
.PHONY : O3dObjLight.i

# target to preprocess a source file
O3dObjLight.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjLight.cc.i
.PHONY : O3dObjLight.cc.i

O3dObjLight.s: O3dObjLight.cc.s
.PHONY : O3dObjLight.s

# target to generate assembly for a file
O3dObjLight.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjLight.cc.s
.PHONY : O3dObjLight.cc.s

O3dObjLine.o: O3dObjLine.cc.o
.PHONY : O3dObjLine.o

# target to build an object file
O3dObjLine.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjLine.cc.o
.PHONY : O3dObjLine.cc.o

O3dObjLine.i: O3dObjLine.cc.i
.PHONY : O3dObjLine.i

# target to preprocess a source file
O3dObjLine.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjLine.cc.i
.PHONY : O3dObjLine.cc.i

O3dObjLine.s: O3dObjLine.cc.s
.PHONY : O3dObjLine.s

# target to generate assembly for a file
O3dObjLine.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjLine.cc.s
.PHONY : O3dObjLine.cc.s

O3dObjNurbs.o: O3dObjNurbs.cc.o
.PHONY : O3dObjNurbs.o

# target to build an object file
O3dObjNurbs.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjNurbs.cc.o
.PHONY : O3dObjNurbs.cc.o

O3dObjNurbs.i: O3dObjNurbs.cc.i
.PHONY : O3dObjNurbs.i

# target to preprocess a source file
O3dObjNurbs.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjNurbs.cc.i
.PHONY : O3dObjNurbs.cc.i

O3dObjNurbs.s: O3dObjNurbs.cc.s
.PHONY : O3dObjNurbs.s

# target to generate assembly for a file
O3dObjNurbs.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjNurbs.cc.s
.PHONY : O3dObjNurbs.cc.s

O3dObjPLibFont.o: O3dObjPLibFont.cc.o
.PHONY : O3dObjPLibFont.o

# target to build an object file
O3dObjPLibFont.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPLibFont.cc.o
.PHONY : O3dObjPLibFont.cc.o

O3dObjPLibFont.i: O3dObjPLibFont.cc.i
.PHONY : O3dObjPLibFont.i

# target to preprocess a source file
O3dObjPLibFont.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPLibFont.cc.i
.PHONY : O3dObjPLibFont.cc.i

O3dObjPLibFont.s: O3dObjPLibFont.cc.s
.PHONY : O3dObjPLibFont.s

# target to generate assembly for a file
O3dObjPLibFont.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPLibFont.cc.s
.PHONY : O3dObjPLibFont.cc.s

O3dObjPoint.o: O3dObjPoint.cc.o
.PHONY : O3dObjPoint.o

# target to build an object file
O3dObjPoint.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPoint.cc.o
.PHONY : O3dObjPoint.cc.o

O3dObjPoint.i: O3dObjPoint.cc.i
.PHONY : O3dObjPoint.i

# target to preprocess a source file
O3dObjPoint.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPoint.cc.i
.PHONY : O3dObjPoint.cc.i

O3dObjPoint.s: O3dObjPoint.cc.s
.PHONY : O3dObjPoint.s

# target to generate assembly for a file
O3dObjPoint.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPoint.cc.s
.PHONY : O3dObjPoint.cc.s

O3dObjPrim.o: O3dObjPrim.cc.o
.PHONY : O3dObjPrim.o

# target to build an object file
O3dObjPrim.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPrim.cc.o
.PHONY : O3dObjPrim.cc.o

O3dObjPrim.i: O3dObjPrim.cc.i
.PHONY : O3dObjPrim.i

# target to preprocess a source file
O3dObjPrim.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPrim.cc.i
.PHONY : O3dObjPrim.cc.i

O3dObjPrim.s: O3dObjPrim.cc.s
.PHONY : O3dObjPrim.s

# target to generate assembly for a file
O3dObjPrim.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjPrim.cc.s
.PHONY : O3dObjPrim.cc.s

O3dObjProps.o: O3dObjProps.cc.o
.PHONY : O3dObjProps.o

# target to build an object file
O3dObjProps.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjProps.cc.o
.PHONY : O3dObjProps.cc.o

O3dObjProps.i: O3dObjProps.cc.i
.PHONY : O3dObjProps.i

# target to preprocess a source file
O3dObjProps.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjProps.cc.i
.PHONY : O3dObjProps.cc.i

O3dObjProps.s: O3dObjProps.cc.s
.PHONY : O3dObjProps.s

# target to generate assembly for a file
O3dObjProps.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjProps.cc.s
.PHONY : O3dObjProps.cc.s

O3dObjShape.o: O3dObjShape.cc.o
.PHONY : O3dObjShape.o

# target to build an object file
O3dObjShape.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjShape.cc.o
.PHONY : O3dObjShape.cc.o

O3dObjShape.i: O3dObjShape.cc.i
.PHONY : O3dObjShape.i

# target to preprocess a source file
O3dObjShape.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjShape.cc.i
.PHONY : O3dObjShape.cc.i

O3dObjShape.s: O3dObjShape.cc.s
.PHONY : O3dObjShape.s

# target to generate assembly for a file
O3dObjShape.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjShape.cc.s
.PHONY : O3dObjShape.cc.s

O3dObjText.o: O3dObjText.cc.o
.PHONY : O3dObjText.o

# target to build an object file
O3dObjText.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjText.cc.o
.PHONY : O3dObjText.cc.o

O3dObjText.i: O3dObjText.cc.i
.PHONY : O3dObjText.i

# target to preprocess a source file
O3dObjText.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjText.cc.i
.PHONY : O3dObjText.cc.i

O3dObjText.s: O3dObjText.cc.s
.PHONY : O3dObjText.s

# target to generate assembly for a file
O3dObjText.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dObjText.cc.s
.PHONY : O3dObjText.cc.s

O3dSelector.o: O3dSelector.cc.o
.PHONY : O3dSelector.o

# target to build an object file
O3dSelector.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dSelector.cc.o
.PHONY : O3dSelector.cc.o

O3dSelector.i: O3dSelector.cc.i
.PHONY : O3dSelector.i

# target to preprocess a source file
O3dSelector.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dSelector.cc.i
.PHONY : O3dSelector.cc.i

O3dSelector.s: O3dSelector.cc.s
.PHONY : O3dSelector.s

# target to generate assembly for a file
O3dSelector.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dSelector.cc.s
.PHONY : O3dSelector.cc.s

O3dViewProps.o: O3dViewProps.cc.o
.PHONY : O3dViewProps.o

# target to build an object file
O3dViewProps.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dViewProps.cc.o
.PHONY : O3dViewProps.cc.o

O3dViewProps.i: O3dViewProps.cc.i
.PHONY : O3dViewProps.i

# target to preprocess a source file
O3dViewProps.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dViewProps.cc.i
.PHONY : O3dViewProps.cc.i

O3dViewProps.s: O3dViewProps.cc.s
.PHONY : O3dViewProps.s

# target to generate assembly for a file
O3dViewProps.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/O3dViewProps.cc.s
.PHONY : O3dViewProps.cc.s

PToken.o: PToken.cc.o
.PHONY : PToken.o

# target to build an object file
PToken.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/PToken.cc.o
.PHONY : PToken.cc.o

PToken.i: PToken.cc.i
.PHONY : PToken.i

# target to preprocess a source file
PToken.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/PToken.cc.i
.PHONY : PToken.cc.i

PToken.s: PToken.cc.s
.PHONY : PToken.s

# target to generate assembly for a file
PToken.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f O3d/CMakeFiles/O3d.dir/build.make O3d/CMakeFiles/O3d.dir/PToken.cc.s
.PHONY : PToken.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... O3d"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... O3dKamera.o"
	@echo "... O3dKamera.i"
	@echo "... O3dKamera.s"
	@echo "... O3dObj.o"
	@echo "... O3dObj.i"
	@echo "... O3dObj.s"
	@echo "... O3dObjBSpline.o"
	@echo "... O3dObjBSpline.i"
	@echo "... O3dObjBSpline.s"
	@echo "... O3dObjBSplineSurf.o"
	@echo "... O3dObjBSplineSurf.i"
	@echo "... O3dObjBSplineSurf.s"
	@echo "... O3dObjBezier.o"
	@echo "... O3dObjBezier.i"
	@echo "... O3dObjBezier.s"
	@echo "... O3dObjFacet.o"
	@echo "... O3dObjFacet.i"
	@echo "... O3dObjFacet.s"
	@echo "... O3dObjLight.o"
	@echo "... O3dObjLight.i"
	@echo "... O3dObjLight.s"
	@echo "... O3dObjLine.o"
	@echo "... O3dObjLine.i"
	@echo "... O3dObjLine.s"
	@echo "... O3dObjNurbs.o"
	@echo "... O3dObjNurbs.i"
	@echo "... O3dObjNurbs.s"
	@echo "... O3dObjPLibFont.o"
	@echo "... O3dObjPLibFont.i"
	@echo "... O3dObjPLibFont.s"
	@echo "... O3dObjPoint.o"
	@echo "... O3dObjPoint.i"
	@echo "... O3dObjPoint.s"
	@echo "... O3dObjPrim.o"
	@echo "... O3dObjPrim.i"
	@echo "... O3dObjPrim.s"
	@echo "... O3dObjProps.o"
	@echo "... O3dObjProps.i"
	@echo "... O3dObjProps.s"
	@echo "... O3dObjShape.o"
	@echo "... O3dObjShape.i"
	@echo "... O3dObjShape.s"
	@echo "... O3dObjText.o"
	@echo "... O3dObjText.i"
	@echo "... O3dObjText.s"
	@echo "... O3dSelector.o"
	@echo "... O3dSelector.i"
	@echo "... O3dSelector.s"
	@echo "... O3dViewProps.o"
	@echo "... O3dViewProps.i"
	@echo "... O3dViewProps.s"
	@echo "... PToken.o"
	@echo "... PToken.i"
	@echo "... PToken.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

