# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phi/DEV/3d/asteroidfighter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phi/DEV/3d/asteroidfighter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles /home/phi/DEV/3d/asteroidfighter/Space/CMakeFiles/progress.marks
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Space/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Space/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Space/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Space/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Space/CMakeFiles/Space.dir/rule:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 Space/CMakeFiles/Space.dir/rule
.PHONY : Space/CMakeFiles/Space.dir/rule

# Convenience name for target.
Space: Space/CMakeFiles/Space.dir/rule
.PHONY : Space

# fast build rule for target.
Space/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/build
.PHONY : Space/fast

ActionsShip.o: ActionsShip.cc.o
.PHONY : ActionsShip.o

# target to build an object file
ActionsShip.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/ActionsShip.cc.o
.PHONY : ActionsShip.cc.o

ActionsShip.i: ActionsShip.cc.i
.PHONY : ActionsShip.i

# target to preprocess a source file
ActionsShip.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/ActionsShip.cc.i
.PHONY : ActionsShip.cc.i

ActionsShip.s: ActionsShip.cc.s
.PHONY : ActionsShip.s

# target to generate assembly for a file
ActionsShip.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/ActionsShip.cc.s
.PHONY : ActionsShip.cc.s

AsteroidesMaker.o: AsteroidesMaker.cc.o
.PHONY : AsteroidesMaker.o

# target to build an object file
AsteroidesMaker.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/AsteroidesMaker.cc.o
.PHONY : AsteroidesMaker.cc.o

AsteroidesMaker.i: AsteroidesMaker.cc.i
.PHONY : AsteroidesMaker.i

# target to preprocess a source file
AsteroidesMaker.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/AsteroidesMaker.cc.i
.PHONY : AsteroidesMaker.cc.i

AsteroidesMaker.s: AsteroidesMaker.cc.s
.PHONY : AsteroidesMaker.s

# target to generate assembly for a file
AsteroidesMaker.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/AsteroidesMaker.cc.s
.PHONY : AsteroidesMaker.cc.s

MinesMaker.o: MinesMaker.cc.o
.PHONY : MinesMaker.o

# target to build an object file
MinesMaker.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/MinesMaker.cc.o
.PHONY : MinesMaker.cc.o

MinesMaker.i: MinesMaker.cc.i
.PHONY : MinesMaker.i

# target to preprocess a source file
MinesMaker.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/MinesMaker.cc.i
.PHONY : MinesMaker.cc.i

MinesMaker.s: MinesMaker.cc.s
.PHONY : MinesMaker.s

# target to generate assembly for a file
MinesMaker.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/MinesMaker.cc.s
.PHONY : MinesMaker.cc.s

Pilot.o: Pilot.cc.o
.PHONY : Pilot.o

# target to build an object file
Pilot.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/Pilot.cc.o
.PHONY : Pilot.cc.o

Pilot.i: Pilot.cc.i
.PHONY : Pilot.i

# target to preprocess a source file
Pilot.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/Pilot.cc.i
.PHONY : Pilot.cc.i

Pilot.s: Pilot.cc.s
.PHONY : Pilot.s

# target to generate assembly for a file
Pilot.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/Pilot.cc.s
.PHONY : Pilot.cc.s

Scene.o: Scene.cc.o
.PHONY : Scene.o

# target to build an object file
Scene.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/Scene.cc.o
.PHONY : Scene.cc.o

Scene.i: Scene.cc.i
.PHONY : Scene.i

# target to preprocess a source file
Scene.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/Scene.cc.i
.PHONY : Scene.cc.i

Scene.s: Scene.cc.s
.PHONY : Scene.s

# target to generate assembly for a file
Scene.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/Scene.cc.s
.PHONY : Scene.cc.s

SceneArtifice.o: SceneArtifice.cc.o
.PHONY : SceneArtifice.o

# target to build an object file
SceneArtifice.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneArtifice.cc.o
.PHONY : SceneArtifice.cc.o

SceneArtifice.i: SceneArtifice.cc.i
.PHONY : SceneArtifice.i

# target to preprocess a source file
SceneArtifice.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneArtifice.cc.i
.PHONY : SceneArtifice.cc.i

SceneArtifice.s: SceneArtifice.cc.s
.PHONY : SceneArtifice.s

# target to generate assembly for a file
SceneArtifice.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneArtifice.cc.s
.PHONY : SceneArtifice.cc.s

SceneAsteroide.o: SceneAsteroide.cc.o
.PHONY : SceneAsteroide.o

# target to build an object file
SceneAsteroide.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneAsteroide.cc.o
.PHONY : SceneAsteroide.cc.o

SceneAsteroide.i: SceneAsteroide.cc.i
.PHONY : SceneAsteroide.i

# target to preprocess a source file
SceneAsteroide.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneAsteroide.cc.i
.PHONY : SceneAsteroide.cc.i

SceneAsteroide.s: SceneAsteroide.cc.s
.PHONY : SceneAsteroide.s

# target to generate assembly for a file
SceneAsteroide.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneAsteroide.cc.s
.PHONY : SceneAsteroide.cc.s

SceneAttack.o: SceneAttack.cc.o
.PHONY : SceneAttack.o

# target to build an object file
SceneAttack.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneAttack.cc.o
.PHONY : SceneAttack.cc.o

SceneAttack.i: SceneAttack.cc.i
.PHONY : SceneAttack.i

# target to preprocess a source file
SceneAttack.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneAttack.cc.i
.PHONY : SceneAttack.cc.i

SceneAttack.s: SceneAttack.cc.s
.PHONY : SceneAttack.s

# target to generate assembly for a file
SceneAttack.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneAttack.cc.s
.PHONY : SceneAttack.cc.s

SceneBase.o: SceneBase.cc.o
.PHONY : SceneBase.o

# target to build an object file
SceneBase.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneBase.cc.o
.PHONY : SceneBase.cc.o

SceneBase.i: SceneBase.cc.i
.PHONY : SceneBase.i

# target to preprocess a source file
SceneBase.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneBase.cc.i
.PHONY : SceneBase.cc.i

SceneBase.s: SceneBase.cc.s
.PHONY : SceneBase.s

# target to generate assembly for a file
SceneBase.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneBase.cc.s
.PHONY : SceneBase.cc.s

SceneChaos.o: SceneChaos.cc.o
.PHONY : SceneChaos.o

# target to build an object file
SceneChaos.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneChaos.cc.o
.PHONY : SceneChaos.cc.o

SceneChaos.i: SceneChaos.cc.i
.PHONY : SceneChaos.i

# target to preprocess a source file
SceneChaos.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneChaos.cc.i
.PHONY : SceneChaos.cc.i

SceneChaos.s: SceneChaos.cc.s
.PHONY : SceneChaos.s

# target to generate assembly for a file
SceneChaos.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneChaos.cc.s
.PHONY : SceneChaos.cc.s

SceneGrotte.o: SceneGrotte.cc.o
.PHONY : SceneGrotte.o

# target to build an object file
SceneGrotte.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneGrotte.cc.o
.PHONY : SceneGrotte.cc.o

SceneGrotte.i: SceneGrotte.cc.i
.PHONY : SceneGrotte.i

# target to preprocess a source file
SceneGrotte.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneGrotte.cc.i
.PHONY : SceneGrotte.cc.i

SceneGrotte.s: SceneGrotte.cc.s
.PHONY : SceneGrotte.s

# target to generate assembly for a file
SceneGrotte.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneGrotte.cc.s
.PHONY : SceneGrotte.cc.s

SceneHammerAnvil.o: SceneHammerAnvil.cc.o
.PHONY : SceneHammerAnvil.o

# target to build an object file
SceneHammerAnvil.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneHammerAnvil.cc.o
.PHONY : SceneHammerAnvil.cc.o

SceneHammerAnvil.i: SceneHammerAnvil.cc.i
.PHONY : SceneHammerAnvil.i

# target to preprocess a source file
SceneHammerAnvil.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneHammerAnvil.cc.i
.PHONY : SceneHammerAnvil.cc.i

SceneHammerAnvil.s: SceneHammerAnvil.cc.s
.PHONY : SceneHammerAnvil.s

# target to generate assembly for a file
SceneHammerAnvil.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneHammerAnvil.cc.s
.PHONY : SceneHammerAnvil.cc.s

SceneLife.o: SceneLife.cc.o
.PHONY : SceneLife.o

# target to build an object file
SceneLife.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneLife.cc.o
.PHONY : SceneLife.cc.o

SceneLife.i: SceneLife.cc.i
.PHONY : SceneLife.i

# target to preprocess a source file
SceneLife.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneLife.cc.i
.PHONY : SceneLife.cc.i

SceneLife.s: SceneLife.cc.s
.PHONY : SceneLife.s

# target to generate assembly for a file
SceneLife.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/SceneLife.cc.s
.PHONY : SceneLife.cc.s

ShipsMaker.o: ShipsMaker.cc.o
.PHONY : ShipsMaker.o

# target to build an object file
ShipsMaker.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/ShipsMaker.cc.o
.PHONY : ShipsMaker.cc.o

ShipsMaker.i: ShipsMaker.cc.i
.PHONY : ShipsMaker.i

# target to preprocess a source file
ShipsMaker.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/ShipsMaker.cc.i
.PHONY : ShipsMaker.cc.i

ShipsMaker.s: ShipsMaker.cc.s
.PHONY : ShipsMaker.s

# target to generate assembly for a file
ShipsMaker.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/ShipsMaker.cc.s
.PHONY : ShipsMaker.cc.s

WorldGame.o: WorldGame.cc.o
.PHONY : WorldGame.o

# target to build an object file
WorldGame.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/WorldGame.cc.o
.PHONY : WorldGame.cc.o

WorldGame.i: WorldGame.cc.i
.PHONY : WorldGame.i

# target to preprocess a source file
WorldGame.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/WorldGame.cc.i
.PHONY : WorldGame.cc.i

WorldGame.s: WorldGame.cc.s
.PHONY : WorldGame.s

# target to generate assembly for a file
WorldGame.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f Space/CMakeFiles/Space.dir/build.make Space/CMakeFiles/Space.dir/WorldGame.cc.s
.PHONY : WorldGame.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Space"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ActionsShip.o"
	@echo "... ActionsShip.i"
	@echo "... ActionsShip.s"
	@echo "... AsteroidesMaker.o"
	@echo "... AsteroidesMaker.i"
	@echo "... AsteroidesMaker.s"
	@echo "... MinesMaker.o"
	@echo "... MinesMaker.i"
	@echo "... MinesMaker.s"
	@echo "... Pilot.o"
	@echo "... Pilot.i"
	@echo "... Pilot.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... SceneArtifice.o"
	@echo "... SceneArtifice.i"
	@echo "... SceneArtifice.s"
	@echo "... SceneAsteroide.o"
	@echo "... SceneAsteroide.i"
	@echo "... SceneAsteroide.s"
	@echo "... SceneAttack.o"
	@echo "... SceneAttack.i"
	@echo "... SceneAttack.s"
	@echo "... SceneBase.o"
	@echo "... SceneBase.i"
	@echo "... SceneBase.s"
	@echo "... SceneChaos.o"
	@echo "... SceneChaos.i"
	@echo "... SceneChaos.s"
	@echo "... SceneGrotte.o"
	@echo "... SceneGrotte.i"
	@echo "... SceneGrotte.s"
	@echo "... SceneHammerAnvil.o"
	@echo "... SceneHammerAnvil.i"
	@echo "... SceneHammerAnvil.s"
	@echo "... SceneLife.o"
	@echo "... SceneLife.i"
	@echo "... SceneLife.s"
	@echo "... ShipsMaker.o"
	@echo "... ShipsMaker.i"
	@echo "... ShipsMaker.s"
	@echo "... WorldGame.o"
	@echo "... WorldGame.i"
	@echo "... WorldGame.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

