# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phi/DEV/3d/asteroidfighter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phi/DEV/3d/asteroidfighter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles /home/phi/DEV/3d/asteroidfighter/U3d/CMakeFiles/progress.marks
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 U3d/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 U3d/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 U3d/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 U3d/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
U3d/CMakeFiles/U3d.dir/rule:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 U3d/CMakeFiles/U3d.dir/rule
.PHONY : U3d/CMakeFiles/U3d.dir/rule

# Convenience name for target.
U3d: U3d/CMakeFiles/U3d.dir/rule
.PHONY : U3d

# fast build rule for target.
U3d/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/build
.PHONY : U3d/fast

Banniere.o: Banniere.cc.o
.PHONY : Banniere.o

# target to build an object file
Banniere.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Banniere.cc.o
.PHONY : Banniere.cc.o

Banniere.i: Banniere.cc.i
.PHONY : Banniere.i

# target to preprocess a source file
Banniere.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Banniere.cc.i
.PHONY : Banniere.cc.i

Banniere.s: Banniere.cc.s
.PHONY : Banniere.s

# target to generate assembly for a file
Banniere.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Banniere.cc.s
.PHONY : Banniere.cc.s

BonusMaker.o: BonusMaker.cc.o
.PHONY : BonusMaker.o

# target to build an object file
BonusMaker.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/BonusMaker.cc.o
.PHONY : BonusMaker.cc.o

BonusMaker.i: BonusMaker.cc.i
.PHONY : BonusMaker.i

# target to preprocess a source file
BonusMaker.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/BonusMaker.cc.i
.PHONY : BonusMaker.cc.i

BonusMaker.s: BonusMaker.cc.s
.PHONY : BonusMaker.s

# target to generate assembly for a file
BonusMaker.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/BonusMaker.cc.s
.PHONY : BonusMaker.cc.s

ContainersMaker.o: ContainersMaker.cc.o
.PHONY : ContainersMaker.o

# target to build an object file
ContainersMaker.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/ContainersMaker.cc.o
.PHONY : ContainersMaker.cc.o

ContainersMaker.i: ContainersMaker.cc.i
.PHONY : ContainersMaker.i

# target to preprocess a source file
ContainersMaker.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/ContainersMaker.cc.i
.PHONY : ContainersMaker.cc.i

ContainersMaker.s: ContainersMaker.cc.s
.PHONY : ContainersMaker.s

# target to generate assembly for a file
ContainersMaker.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/ContainersMaker.cc.s
.PHONY : ContainersMaker.cc.s

ObjPrimPart.o: ObjPrimPart.cc.o
.PHONY : ObjPrimPart.o

# target to build an object file
ObjPrimPart.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/ObjPrimPart.cc.o
.PHONY : ObjPrimPart.cc.o

ObjPrimPart.i: ObjPrimPart.cc.i
.PHONY : ObjPrimPart.i

# target to preprocess a source file
ObjPrimPart.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/ObjPrimPart.cc.i
.PHONY : ObjPrimPart.cc.i

ObjPrimPart.s: ObjPrimPart.cc.s
.PHONY : ObjPrimPart.s

# target to generate assembly for a file
ObjPrimPart.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/ObjPrimPart.cc.s
.PHONY : ObjPrimPart.cc.s

Sky.o: Sky.cc.o
.PHONY : Sky.o

# target to build an object file
Sky.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Sky.cc.o
.PHONY : Sky.cc.o

Sky.i: Sky.cc.i
.PHONY : Sky.i

# target to preprocess a source file
Sky.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Sky.cc.i
.PHONY : Sky.cc.i

Sky.s: Sky.cc.s
.PHONY : Sky.s

# target to generate assembly for a file
Sky.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Sky.cc.s
.PHONY : Sky.cc.s

SpriteExplosion.o: SpriteExplosion.cc.o
.PHONY : SpriteExplosion.o

# target to build an object file
SpriteExplosion.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/SpriteExplosion.cc.o
.PHONY : SpriteExplosion.cc.o

SpriteExplosion.i: SpriteExplosion.cc.i
.PHONY : SpriteExplosion.i

# target to preprocess a source file
SpriteExplosion.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/SpriteExplosion.cc.i
.PHONY : SpriteExplosion.cc.i

SpriteExplosion.s: SpriteExplosion.cc.s
.PHONY : SpriteExplosion.s

# target to generate assembly for a file
SpriteExplosion.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/SpriteExplosion.cc.s
.PHONY : SpriteExplosion.cc.s

Tourelle.o: Tourelle.cc.o
.PHONY : Tourelle.o

# target to build an object file
Tourelle.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Tourelle.cc.o
.PHONY : Tourelle.cc.o

Tourelle.i: Tourelle.cc.i
.PHONY : Tourelle.i

# target to preprocess a source file
Tourelle.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Tourelle.cc.i
.PHONY : Tourelle.cc.i

Tourelle.s: Tourelle.cc.s
.PHONY : Tourelle.s

# target to generate assembly for a file
Tourelle.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/Tourelle.cc.s
.PHONY : Tourelle.cc.s

WeaponsMaker.o: WeaponsMaker.cc.o
.PHONY : WeaponsMaker.o

# target to build an object file
WeaponsMaker.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/WeaponsMaker.cc.o
.PHONY : WeaponsMaker.cc.o

WeaponsMaker.i: WeaponsMaker.cc.i
.PHONY : WeaponsMaker.i

# target to preprocess a source file
WeaponsMaker.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/WeaponsMaker.cc.i
.PHONY : WeaponsMaker.cc.i

WeaponsMaker.s: WeaponsMaker.cc.s
.PHONY : WeaponsMaker.s

# target to generate assembly for a file
WeaponsMaker.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f U3d/CMakeFiles/U3d.dir/build.make U3d/CMakeFiles/U3d.dir/WeaponsMaker.cc.s
.PHONY : WeaponsMaker.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... U3d"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Banniere.o"
	@echo "... Banniere.i"
	@echo "... Banniere.s"
	@echo "... BonusMaker.o"
	@echo "... BonusMaker.i"
	@echo "... BonusMaker.s"
	@echo "... ContainersMaker.o"
	@echo "... ContainersMaker.i"
	@echo "... ContainersMaker.s"
	@echo "... ObjPrimPart.o"
	@echo "... ObjPrimPart.i"
	@echo "... ObjPrimPart.s"
	@echo "... Sky.o"
	@echo "... Sky.i"
	@echo "... Sky.s"
	@echo "... SpriteExplosion.o"
	@echo "... SpriteExplosion.i"
	@echo "... SpriteExplosion.s"
	@echo "... Tourelle.o"
	@echo "... Tourelle.i"
	@echo "... Tourelle.s"
	@echo "... WeaponsMaker.o"
	@echo "... WeaponsMaker.i"
	@echo "... WeaponsMaker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

