TARGET=libT3d.a

SRCS = \
	T3dBox.cc \
	T3dFontRaster.cc \
	T3dLoadImg.cc \
	T3dTransf.cc \
	T3dCalcul.cc \
	T3dLoadBmp.cc \
	T3dPrimitiv.cc \
	T3dVect3D.cc	\
	T3dColor.cc \
	T3dLoadGif.cc \
	T3dTexture.cc

OBJS =  $(SRCS:.cc=.o)


HDRS = $(SRCS:.cc=.h)


# /usr/lib/x86_64-linux-gnu
# ---------------------------------------------------

CFLAGS=  ${CC_DEBUG} -g -std=c++11 -Wall  -m64  -O3 -pthread -D_POSIX_PTHREAD_SEMANTICS -m64 

CINCLUDE= -I. -I..

# -I/usr/openwin/include   -I${DIR_OPENGL_INC} -I${DIR_GLUT_INC} -I${DIR_PLIB_INC}

COMPILO=gcc

# ---------------------------------------------------

all:: start	

all:: $(OBJS)

all::	$(TARGET)

start:
		rm  -f $(TARGET)

clean::
		rm	 -f *.o	*.a



# ---------------------------------------------------
# Compilation
.cc.o:
		gcc -O2 $(CFLAGS) $(CINCLUDE)  -c $*.cc 
 

# ---------------------------------------------------
# Library

$(TARGET):
		rm -f $(TARGET) 
	 	ar cq $(TARGET) $(OBJS)
		ranlib $(TARGET)


# ---------------------------------------------------
# Depends
DEPEND = makedepend

ALLDEFINES=$CINCLUDE

depend:: $(SRCS) $(HDRS)
	$(DEPEND)  -s "# DO NOT DELETE" -- $(ALLDEFINES) -- $(SRCS)
dependlocal:: $(SRCS) $(HEADERS)
	$(DEPEND)  -s "# DO NOT DELETE" -- $(ALLDEFINES) -- $(SRCS)
