# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phi/DEV/3d/asteroidfighter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phi/DEV/3d/asteroidfighter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles /home/phi/DEV/3d/asteroidfighter/T3d/CMakeFiles/progress.marks
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 T3d/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phi/DEV/3d/asteroidfighter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 T3d/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 T3d/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 T3d/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
T3d/CMakeFiles/T3d.dir/rule:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f CMakeFiles/Makefile2 T3d/CMakeFiles/T3d.dir/rule
.PHONY : T3d/CMakeFiles/T3d.dir/rule

# Convenience name for target.
T3d: T3d/CMakeFiles/T3d.dir/rule
.PHONY : T3d

# fast build rule for target.
T3d/fast:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/build
.PHONY : T3d/fast

T3dBox.o: T3dBox.cc.o
.PHONY : T3dBox.o

# target to build an object file
T3dBox.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dBox.cc.o
.PHONY : T3dBox.cc.o

T3dBox.i: T3dBox.cc.i
.PHONY : T3dBox.i

# target to preprocess a source file
T3dBox.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dBox.cc.i
.PHONY : T3dBox.cc.i

T3dBox.s: T3dBox.cc.s
.PHONY : T3dBox.s

# target to generate assembly for a file
T3dBox.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dBox.cc.s
.PHONY : T3dBox.cc.s

T3dCalcul.o: T3dCalcul.cc.o
.PHONY : T3dCalcul.o

# target to build an object file
T3dCalcul.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dCalcul.cc.o
.PHONY : T3dCalcul.cc.o

T3dCalcul.i: T3dCalcul.cc.i
.PHONY : T3dCalcul.i

# target to preprocess a source file
T3dCalcul.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dCalcul.cc.i
.PHONY : T3dCalcul.cc.i

T3dCalcul.s: T3dCalcul.cc.s
.PHONY : T3dCalcul.s

# target to generate assembly for a file
T3dCalcul.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dCalcul.cc.s
.PHONY : T3dCalcul.cc.s

T3dColor.o: T3dColor.cc.o
.PHONY : T3dColor.o

# target to build an object file
T3dColor.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dColor.cc.o
.PHONY : T3dColor.cc.o

T3dColor.i: T3dColor.cc.i
.PHONY : T3dColor.i

# target to preprocess a source file
T3dColor.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dColor.cc.i
.PHONY : T3dColor.cc.i

T3dColor.s: T3dColor.cc.s
.PHONY : T3dColor.s

# target to generate assembly for a file
T3dColor.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dColor.cc.s
.PHONY : T3dColor.cc.s

T3dFontRaster.o: T3dFontRaster.cc.o
.PHONY : T3dFontRaster.o

# target to build an object file
T3dFontRaster.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dFontRaster.cc.o
.PHONY : T3dFontRaster.cc.o

T3dFontRaster.i: T3dFontRaster.cc.i
.PHONY : T3dFontRaster.i

# target to preprocess a source file
T3dFontRaster.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dFontRaster.cc.i
.PHONY : T3dFontRaster.cc.i

T3dFontRaster.s: T3dFontRaster.cc.s
.PHONY : T3dFontRaster.s

# target to generate assembly for a file
T3dFontRaster.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dFontRaster.cc.s
.PHONY : T3dFontRaster.cc.s

T3dLoadBmp.o: T3dLoadBmp.cc.o
.PHONY : T3dLoadBmp.o

# target to build an object file
T3dLoadBmp.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadBmp.cc.o
.PHONY : T3dLoadBmp.cc.o

T3dLoadBmp.i: T3dLoadBmp.cc.i
.PHONY : T3dLoadBmp.i

# target to preprocess a source file
T3dLoadBmp.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadBmp.cc.i
.PHONY : T3dLoadBmp.cc.i

T3dLoadBmp.s: T3dLoadBmp.cc.s
.PHONY : T3dLoadBmp.s

# target to generate assembly for a file
T3dLoadBmp.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadBmp.cc.s
.PHONY : T3dLoadBmp.cc.s

T3dLoadGif.o: T3dLoadGif.cc.o
.PHONY : T3dLoadGif.o

# target to build an object file
T3dLoadGif.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadGif.cc.o
.PHONY : T3dLoadGif.cc.o

T3dLoadGif.i: T3dLoadGif.cc.i
.PHONY : T3dLoadGif.i

# target to preprocess a source file
T3dLoadGif.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadGif.cc.i
.PHONY : T3dLoadGif.cc.i

T3dLoadGif.s: T3dLoadGif.cc.s
.PHONY : T3dLoadGif.s

# target to generate assembly for a file
T3dLoadGif.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadGif.cc.s
.PHONY : T3dLoadGif.cc.s

T3dLoadImg.o: T3dLoadImg.cc.o
.PHONY : T3dLoadImg.o

# target to build an object file
T3dLoadImg.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadImg.cc.o
.PHONY : T3dLoadImg.cc.o

T3dLoadImg.i: T3dLoadImg.cc.i
.PHONY : T3dLoadImg.i

# target to preprocess a source file
T3dLoadImg.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadImg.cc.i
.PHONY : T3dLoadImg.cc.i

T3dLoadImg.s: T3dLoadImg.cc.s
.PHONY : T3dLoadImg.s

# target to generate assembly for a file
T3dLoadImg.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dLoadImg.cc.s
.PHONY : T3dLoadImg.cc.s

T3dPrimitiv.o: T3dPrimitiv.cc.o
.PHONY : T3dPrimitiv.o

# target to build an object file
T3dPrimitiv.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dPrimitiv.cc.o
.PHONY : T3dPrimitiv.cc.o

T3dPrimitiv.i: T3dPrimitiv.cc.i
.PHONY : T3dPrimitiv.i

# target to preprocess a source file
T3dPrimitiv.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dPrimitiv.cc.i
.PHONY : T3dPrimitiv.cc.i

T3dPrimitiv.s: T3dPrimitiv.cc.s
.PHONY : T3dPrimitiv.s

# target to generate assembly for a file
T3dPrimitiv.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dPrimitiv.cc.s
.PHONY : T3dPrimitiv.cc.s

T3dTexture.o: T3dTexture.cc.o
.PHONY : T3dTexture.o

# target to build an object file
T3dTexture.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dTexture.cc.o
.PHONY : T3dTexture.cc.o

T3dTexture.i: T3dTexture.cc.i
.PHONY : T3dTexture.i

# target to preprocess a source file
T3dTexture.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dTexture.cc.i
.PHONY : T3dTexture.cc.i

T3dTexture.s: T3dTexture.cc.s
.PHONY : T3dTexture.s

# target to generate assembly for a file
T3dTexture.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dTexture.cc.s
.PHONY : T3dTexture.cc.s

T3dTransf.o: T3dTransf.cc.o
.PHONY : T3dTransf.o

# target to build an object file
T3dTransf.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dTransf.cc.o
.PHONY : T3dTransf.cc.o

T3dTransf.i: T3dTransf.cc.i
.PHONY : T3dTransf.i

# target to preprocess a source file
T3dTransf.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dTransf.cc.i
.PHONY : T3dTransf.cc.i

T3dTransf.s: T3dTransf.cc.s
.PHONY : T3dTransf.s

# target to generate assembly for a file
T3dTransf.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dTransf.cc.s
.PHONY : T3dTransf.cc.s

T3dVect3D.o: T3dVect3D.cc.o
.PHONY : T3dVect3D.o

# target to build an object file
T3dVect3D.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dVect3D.cc.o
.PHONY : T3dVect3D.cc.o

T3dVect3D.i: T3dVect3D.cc.i
.PHONY : T3dVect3D.i

# target to preprocess a source file
T3dVect3D.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dVect3D.cc.i
.PHONY : T3dVect3D.cc.i

T3dVect3D.s: T3dVect3D.cc.s
.PHONY : T3dVect3D.s

# target to generate assembly for a file
T3dVect3D.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/T3dVect3D.cc.s
.PHONY : T3dVect3D.cc.s

trackball.o: trackball.cc.o
.PHONY : trackball.o

# target to build an object file
trackball.cc.o:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/trackball.cc.o
.PHONY : trackball.cc.o

trackball.i: trackball.cc.i
.PHONY : trackball.i

# target to preprocess a source file
trackball.cc.i:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/trackball.cc.i
.PHONY : trackball.cc.i

trackball.s: trackball.cc.s
.PHONY : trackball.s

# target to generate assembly for a file
trackball.cc.s:
	cd /home/phi/DEV/3d/asteroidfighter && $(MAKE) -f T3d/CMakeFiles/T3d.dir/build.make T3d/CMakeFiles/T3d.dir/trackball.cc.s
.PHONY : trackball.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... T3d"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... T3dBox.o"
	@echo "... T3dBox.i"
	@echo "... T3dBox.s"
	@echo "... T3dCalcul.o"
	@echo "... T3dCalcul.i"
	@echo "... T3dCalcul.s"
	@echo "... T3dColor.o"
	@echo "... T3dColor.i"
	@echo "... T3dColor.s"
	@echo "... T3dFontRaster.o"
	@echo "... T3dFontRaster.i"
	@echo "... T3dFontRaster.s"
	@echo "... T3dLoadBmp.o"
	@echo "... T3dLoadBmp.i"
	@echo "... T3dLoadBmp.s"
	@echo "... T3dLoadGif.o"
	@echo "... T3dLoadGif.i"
	@echo "... T3dLoadGif.s"
	@echo "... T3dLoadImg.o"
	@echo "... T3dLoadImg.i"
	@echo "... T3dLoadImg.s"
	@echo "... T3dPrimitiv.o"
	@echo "... T3dPrimitiv.i"
	@echo "... T3dPrimitiv.s"
	@echo "... T3dTexture.o"
	@echo "... T3dTexture.i"
	@echo "... T3dTexture.s"
	@echo "... T3dTransf.o"
	@echo "... T3dTransf.i"
	@echo "... T3dTransf.s"
	@echo "... T3dVect3D.o"
	@echo "... T3dVect3D.i"
	@echo "... T3dVect3D.s"
	@echo "... trackball.o"
	@echo "... trackball.i"
	@echo "... trackball.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/phi/DEV/3d/asteroidfighter && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

